name: Deploy German

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 0 1 * *"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set current date
        run: echo "DATETIME=$(date +'%Y_%m_%d_%H_%M')" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy files via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          source: "*"
          target: "/var/www/silke-skopp"
          rm: true
          password: ${{ secrets.SSH_PASSWORD }}
